## @file
# Azure Pipeline build file for a build using Windows and VS2019
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
trigger:
- main

schedules:
- cron: "0 8 * * 0"   # Sun/Wed at 1AM Pacific
  displayName: Sun Build
  branches:
    include:
    - main
  always: true          # Always build, even if no changes

pr:
- main

jobs:
- template: templates/pr-gate-build-job.yml
  parameters:
    tool_chain_tag: 'VS2022'
    vm_image: 'windows-latest'
    arch_list: "IA32,X64"
